[project]
name = "OrgAlkCalc"
version = "0.1.1"
authors = [
  { name="Charles Turner", email="charlesturner0987@gmail.com" },
  { name="Dan Kerr", email="dankerr30@gmail.com" },
]
description = "A package for automatically computing organic alkalinity"
readme = "README.md"
license = { file="LICENCE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/charles-turner-1/OrgAlkCalc"
"Bug Tracker" = "https://github.com/charles-turner-1/OrgAlkCalc/issues"